In [7]:
import numpy as np
import glob
import pandas as pd

In [8]:
file_pattern = "logs/wide_*_select_scan.perf"
all_files = glob.glob(file_pattern)

In [9]:
all_files

['logs/wide_1_select_scan.perf',
 'logs/wide_2_select_scan.perf',
 'logs/wide_3_select_scan.perf',
 'logs/wide_4_select_scan.perf',
 'logs/wide_5_select_scan.perf',
 'logs/wide_6_select_scan.perf',
 'logs/wide_7_select_scan.perf',
 'logs/wide_8_select_scan.perf']

In [10]:
df_list = []
for file_path in all_files:
    temp_df = pd.read_csv(file_path)
    temp_df['source_file'] = file_path
    df_list.append(temp_df)

In [12]:
df_all = pd.concat(df_list, ignore_index=True)

In [19]:
df_all['ipc'] = df_all['instructions'] / df_all['cpu_cycles']
df_all['llc_miss_rate'] = df_all['llc_misses'] / df_all['llc_references']
df_all['latency_ms'] = df_all['latency'] / 1e6

In [20]:
df_all

,llc_references,llc_misses,cpu_cycles,instructions,latency,l1d_read_miss,source_file,ipc,llc_miss_rate,latency_s,latency_ms
0,7732398,8446,399701833,1363994656,164634496,4553157,logs/wide_1_select_scan.perf,3.412530,0.001092,0.164634,164.634496
1,7262883,7069,399267083,1363994665,164298811,4379203,logs/wide_1_select_scan.perf,3.416246,0.000973,0.164299,164.298811
2,7841126,7759,400685448,1363994658,164980402,4514888,logs/wide_1_select_scan.perf,3.404153,0.000990,0.164980,164.980402
3,7372098,9923,401176800,1363994659,167052217,4396728,logs/wide_1_select_scan.perf,3.399984,0.001346,0.167052,167.052217
4,7598836,8564,399520923,1363994678,165656232,4522962,logs/wide_1_select_scan.perf,3.414076,0.001127,0.165656,165.656232
...,...,...,...,...,...,...,...,...,...,...,...
795,20246045,13166,371147413,1123009277,394891784,9781845,logs/wide_8_select_scan.perf,3.025777,0.000650,0.394892,394.891784
796,20630097,9920,371532854,1122749990,393752277,9829976,logs/wide_8_select_scan.perf,3.021940,0.000481,0.393752,393.752277
797,20335044,7745,374482143,1123009265,394107349,9942879,logs/wide_8_select_scan.perf,2.998833,0.000381,0.394107,394.107349
798,20348919,10062,375729989,1123009289,396297997,9406513,logs/wide_8_select_scan.perf,2.988873,0.000494,0.396298,396.297997
799,20953456,7270,379778186,1123009275,394014233,9912929,logs/wide_8_select_scan.perf,2.957014,0.000347,0.394014,394.014233

In [27]:
metrics = ['ipc', 'llc_miss_rate', 'latency_ms', 'l1d_read_miss']
df_all.groupby('source_file')[metrics].std() / df_all.groupby('source_file')[metrics].mean() * 100

,ipc,llc_miss_rate,latency_ms,l1d_read_miss
source_file,,,,
logs/wide_1_select_scan.perf,0.470489,19.315000,0.584179,3.121369
logs/wide_2_select_scan.perf,0.257106,16.541084,0.693653,1.932905
logs/wide_3_select_scan.perf,0.320686,22.234179,1.693914,2.465518
logs/wide_4_select_scan.perf,0.274590,16.836396,0.795921,2.374141
logs/wide_5_select_scan.perf,0.507011,22.228301,0.473522,2.674770
logs/wide_6_select_scan.perf,0.470375,17.611464,0.511987,1.415297
logs/wide_7_select_scan.perf,0.506201,19.256933,0.573259,1.750289
logs/wide_8_select_scan.perf,0.592302,19.697750,1.570699,2.086452

In [29]:
summary = df_all.groupby('source_file')[metrics].mean()

In [30]:
summary

,ipc,llc_miss_rate,latency_ms,l1d_read_miss
source_file,,,,
logs/wide_1_select_scan.perf,3.408924,0.001116,165.597287,4380698.59
logs/wide_2_select_scan.perf,3.281185,0.000790,187.558327,5327587.63
logs/wide_3_select_scan.perf,3.213494,0.001023,219.631891,5966399.41
logs/wide_4_select_scan.perf,3.102628,0.000624,249.840908,6851232.64
logs/wide_5_select_scan.perf,3.009266,0.001007,289.029790,7484351.82
logs/wide_6_select_scan.perf,3.000895,0.000688,323.325448,8467956.47
logs/wide_7_select_scan.perf,2.966360,0.000943,356.999147,9089307.85
logs/wide_8_select_scan.perf,3.010928,0.000569,395.690626,9709301.07